project_id = "vrrupflvbdfpywdhbqzt"

[functions.predict-node-performance]
verify_jwt = false

[functions.optimize-bandwidth]
verify_jwt = false

[functions.predict-maintenance]
verify_jwt = false

[functions.hedera-create-token]
verify_jwt = true

[functions.hedera-transfer-token]
verify_jwt = true

[functions.hedera-get-balance]
verify_jwt = true
