name: Hedera Demo

on:
  workflow_dispatch:

jobs:
  run-demo:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Install deps
        run: |
          npm ci || npm i
          npm i --no-save @hashgraph/sdk tsx

      - name: Run HCS + HTS demo
        env:
          HEDERA_OPERATOR_ID: ${{ secrets.HEDERA_OPERATOR_ID }}
          HEDERA_OPERATOR_KEY: ${{ secrets.HEDERA_OPERATOR_KEY }}
        run: npx tsx scripts/hcs-demo.ts
